akashic-games/headless-akashic

CHANGELOG.md
package-lock.json
package.json
src/GameContext.ts
src/__tests__/run.spec.ts
src/index.ts
src/loggers/DefaultLogger.ts
src/loggers/VerboseLogger.ts
src/loggers/index.ts

* `GameContextParameterObject#verbose` を追加します。
* この値を true にした場合のみコンソール出力するようにします。

`GameContextParameterObject#verbose` を追加

---

CHANGELOG.md
README.md
fixtures/empty-v3/game.json
fixtures/empty-v3/main.js
package-lock.json
package.json
src/GameClient.ts
src/GameContext.ts
src/__tests__/run.spec.ts
src/constants.ts
tsconfig.json

feat: support to launch empty game

---

.github/workflows/test.yml
CHANGELOG.md
README.md
package-lock.json
package.json
src/GameClient.ts
src/GameContext.ts
src/__tests__/run.spec.ts
src/index.ts
src/types.ts

* headless-driver@1.7.0 に追従
* `GameContextParameterObject#renderingMode` を追加
* `GameClient#getPrimarySurfaceCanvas()` を追加
* `GameClient#g` を追加
* **[BREAKING]** `GameClient`, `GameClientParameterObject` の generics の型を変更

[BREAKING] ゲーム画面の出力機能の追加など

---

.github/workflows/release.yml

main ブランチへのマージ時にリリースを実行するワークフローを追加します。

リリースワークフローを追加

---

.github/workflows/release.yml

`"` を `'` に修正します。
自明のためセルフマージします。
参考: https://docs.github.com/ja/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles

fix(ci): `"` -> `'`

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/GameClient.ts
src/__tests__/run.spec.ts

ダミーのアセットを作成する `GameContext#createDummyImageAsset()`, `GameContext#createDummyAudioAsset()` を追加します。

ダミーのアセットを作成するメソッドの追加

---

.github/workflows/release.yml

GitHub Actions のリリース処理を https://github.com/akashic-games/action-release に移行したため、その追従です。

chore(ci): change repo for releasing action

---

CHANGELOG.md
package-lock.json
package.json
src/types.ts

https://github.com/akashic-games/headless-driver/pull/309 を取り込みます。
自明な変更のためセルフマージします。

feat: follow headless-driver@1.11.0

---

src/loggers/DefaultLogger.ts
src/loggers/VerboseLogger.ts

eslint-config@1.1.0 による自動修正
- import type の使用
自動修正のため renovate の PR #44 へセルフマージします。

Fix by eslint

---

renovate.json

renovate のスケジュールを non-office Time へ、akashic 関連は `at any time` に変更します。

Fix schedule in renovate.json

---

renovate.json

`@akashic` 関連のモジュールの patch が更新された際にバージョンを更新して automerge するように修正します。

fix: automerge と bumpVersion 対応

---

.github/workflows/release.yml
.github/workflows/test.yml

CI の Node のバージョンを 14, 16 に更新します。すでに同様の修正をレビュー済み (https://github.com/akashic-games/trigger/pull/38, https://github.com/akashic-games/game-configuration/pull/28) のためセルフマージします。

chore: CI の Node のバージョンを 14, 16 に更新

---

CHANGELOG.md
README.md
package-lock.json
package.json
tsconfig.json

node-canvas を optionalDependencies へ移動します。

chore(deps): node-canvas を optionalDependencies へ移動

---

.github/workflows/release.yml
.github/workflows/test.yml

Updtate CI node version

---

CHANGELOG.md
package-lock.json
package.json

https://github.com/akashic-games/headless-driver/pull/621 に追従します。
モジュール更新のみで自明の変更のためセルフマージします。

chore: follow headless-driver@2.10.0

---

CHANGELOG.md
package-lock.json
package.json
src/GameClient.ts
src/GameContext.ts
src/__tests__/fixtures/helloworld/script/main.js
src/__tests__/run.spec.ts
src/constants.ts
src/types.ts

* `GameClient#sendJoinEvent()`, `GameClient#sendLeaveEvent()` を追加します。
* `GameClient#sendMessageEvent()` のテストを追加します。
* フォーマッタ更新のため一部のファイルに差分が出ていますがコードに変更はありません。

feat: `GameClient#sendJoinEvent()`, `GameClient#sendLeaveEvent()` の追加

---

CHANGELOG.md
package-lock.json
package.json
src/GameContext.ts
src/__tests__/run.spec.ts

`GameClient` の生成時に `gameArgs` を渡せるように機能追加します。

feat: support passing gameArgs

---

CHANGELOG.md
package-lock.json
package.json
src/GameContext.ts

`GameContext#getGameClient()`, `GameContext#createPassiveGameClient()` 時に `player` を渡せるように修正します。

feat: support passing player

---

CHANGELOG.md
package-lock.json
package.json
src/GameContext.ts
src/__tests__/fixtures/raise-event/game.json
src/__tests__/fixtures/raise-event/main.js
src/__tests__/run.spec.ts

resolves #97 
`GameContext#advance()` を利用すると、経過中に発生した任意のイベントの処理が (`advance()` 実行後の) 次のフレームまで遅延されてしまうことを明記します。
また、それぞれのインスタンスの処理を1フレームずつ、指定ミリ秒分だけ進める `GameContext#advanceEach()` を追加します。

fix: add `GameContext#advanceEach()`

---

CHANGELOG.md
package-lock.json
package.json
src/GameContext.ts
src/__tests__/run.spec.ts

- `headless-driver@2.14.0` に追従します。
- `GameContext#step()` の戻り値の型を `Promise<void>` に変更します。

feat: follow headless-driver@2.14.0

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/GameClient.ts
src/GameContext.ts
src/__tests__/helpers/SilentLogger.ts

https://github.com/akashic-games/headless-driver/pull/676 に追従します。

feat: follow headless-driver@2.16.0
